export const homeSchool =
  "Pendik İTO Şehit Ahmet Aslanhan Anadolu İmam Hatip Lisesi";

export const highSchools = [
  homeSchool,
  "Pendik Anadolu İmam Hatip Lisesi",
  "Kartal Anadolu İmam Hatip Lisesi",
  "Ümraniye Anadolu İmam Hatip Lisesi",
  "Ataşehir Anadolu İmam Hatip Lisesi",
  "Kadıköy Anadolu İmam Hatip Lisesi",
  "İstanbul Atatürk Fen Lisesi",
  "Kabataş Erkek Lisesi",
  "İstanbul Erkek Lisesi",
  "Cağaloğlu Anadolu Lisesi",
];

export const highSchoolYears = ["Hazırlık", "9. sınıf", "10. sınıf", "11. sınıf", "12. sınıf"];

export const highSchoolTracks = [
  "Anadolu İmam Hatip",
  "Fen Bilimleri",
  "Sosyal Bilimler",
  "Yabancı Dil",
];

export const universityYears = [
  "Hazırlık",
  "1. sınıf",
  "2. sınıf",
  "3. sınıf",
  "4. sınıf",
  "5. sınıf",
  "6. sınıf",
  "Yüksek lisans",
  "Doktora",
];

export const graduateYears = Array.from({ length: 20 }, (_, index) => String(2026 - index));

export const universities = [  "Abdullah Gül Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ankara Yıldırım Beyazıt Üniversitesi",
  "Atatürk Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Başkent Üniversitesi",
  "Beykent Üniversitesi",
  "Bezmiâlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bilkent Üniversitesi",
  "Biruni Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çukurova Üniversitesi",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Hacettepe Üniversitesi",
  "Haliç Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Hitit Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İnönü Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Nişantaşı Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Topkapı Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Kocaeli Üniversitesi",
  "Koç Üniversitesi",
  "Konya Gıda ve Tarım Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Marmara Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Özyeğin Üniversitesi",
  "Pamukkale Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sakarya Üniversitesi",
  "Selçuk Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "TED Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Trakya Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
];

export const departments = [
  "İlahiyat",
  "İslami İlimler",
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Ebelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Hukuk",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Uluslararası İlişkiler",
  "İşletme",
  "İktisat",
  "Maliye",
  "Finans",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Psikoloji",
  "Sosyoloji",
  "Tarih",
  "Felsefe",
  "Türk Dili ve Edebiyatı",
  "Arap Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "Mütercim-Tercümanlık",
  "Gazetecilik",
  "Halkla İlişkiler ve Tanıtım",
  "Radyo, Televizyon ve Sinema",
  "İletişim",
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Yapay Zeka Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Endüstri Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Mekatronik Mühendisliği",
  "Bilgisayar Bilimleri",
  "Yönetim Bilişim Sistemleri",
  "Mimarlık",
  "İç Mimarlık",
  "Şehir ve Bölge Planlama",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Sınıf Öğretmenliği",
  "Okul Öncesi Öğretmenliği",
  "İngilizce Öğretmenliği",
  "İlköğretim Matematik Öğretmenliği",
  "Din Kültürü ve Ahlak Bilgisi Öğretmenliği",
  "Arapça Öğretmenliği",
  "Meslek Yüksekokulu",
  "Açıköğretim",
];
